site_name: Hesiod Documentation

theme:
    name: null
    custom_dir: 'docs/custom-theme/'

nav:
  - 'Start Here':
    - 'index.md'
  - 'Node Reference':
    - 'node_reference/categories.md'
    - 'node_reference/nodes/Abs.md'
    - 'node_reference/nodes/AbsSmooth.md'
    - 'node_reference/nodes/AccumulationCurvature.md'
    - 'node_reference/nodes/Badlands.md'
    - 'node_reference/nodes/BasaltField.md'
    - 'node_reference/nodes/Blend.md'
    - 'node_reference/nodes/Blend3.md'
    - 'node_reference/nodes/BlendPoissonBf.md'
    - 'node_reference/nodes/Border.md'
    - 'node_reference/nodes/Broadcast.md'
    - 'node_reference/nodes/Brush.md'
    - 'node_reference/nodes/Bulkify.md'
    - 'node_reference/nodes/Bump.md'
    - 'node_reference/nodes/BumpLorentzian.md'
    - 'node_reference/nodes/Caldera.md'
    - 'node_reference/nodes/Clamp.md'
    - 'node_reference/nodes/ClampOblique.md'
    - 'node_reference/nodes/Closing.md'
    - 'node_reference/nodes/Cloud.md'
    - 'node_reference/nodes/CloudFromCsv.md'
    - 'node_reference/nodes/CloudLattice.md'
    - 'node_reference/nodes/CloudMerge.md'
    - 'node_reference/nodes/CloudRandom.md'
    - 'node_reference/nodes/CloudRandomDensity.md'
    - 'node_reference/nodes/CloudRandomDistance.md'
    - 'node_reference/nodes/CloudRandomPowerLaw.md'
    - 'node_reference/nodes/CloudRandomWeibull.md'
    - 'node_reference/nodes/CloudRemapValues.md'
    - 'node_reference/nodes/CloudSDF.md'
    - 'node_reference/nodes/CloudSetValuesFromBorderDistance.md'
    - 'node_reference/nodes/CloudSetValuesFromHeightmap.md'
    - 'node_reference/nodes/CloudSetValuesFromMinDistance.md'
    - 'node_reference/nodes/CloudShuffle.md'
    - 'node_reference/nodes/CloudToArrayInterp.md'
    - 'node_reference/nodes/CloudToPath.md'
    - 'node_reference/nodes/CloudToVectors.md'
    - 'node_reference/nodes/CoastalErosionDiffusion.md'
    - 'node_reference/nodes/CoastalErosionProfile.md'
    - 'node_reference/nodes/ColorizeCmap.md'
    - 'node_reference/nodes/ColorizeGradient.md'
    - 'node_reference/nodes/ColorizeSolid.md'
    - 'node_reference/nodes/CombineMask.md'
    - 'node_reference/nodes/Cone.md'
    - 'node_reference/nodes/ConeComplex.md'
    - 'node_reference/nodes/ConeSigmoid.md'
    - 'node_reference/nodes/Constant.md'
    - 'node_reference/nodes/ConvolveSVD.md'
    - 'node_reference/nodes/Cos.md'
    - 'node_reference/nodes/Crater.md'
    - 'node_reference/nodes/CurvatureMean.md'
    - 'node_reference/nodes/Debug.md'
    - 'node_reference/nodes/Dendry.md'
    - 'node_reference/nodes/DepressionFilling.md'
    - 'node_reference/nodes/Detrend.md'
    - 'node_reference/nodes/DiffusionLimitedAggregation.md'
    - 'node_reference/nodes/Dilation.md'
    - 'node_reference/nodes/DirectionalBlur.md'
    - 'node_reference/nodes/DistanceTransform.md'
    - 'node_reference/nodes/Equalize.md'
    - 'node_reference/nodes/Erosion.md'
    - 'node_reference/nodes/ExpandShrink.md'
    - 'node_reference/nodes/ExportAsCubemap.md'
    - 'node_reference/nodes/ExportAsset.md'
    - 'node_reference/nodes/ExportCloud.md'
    - 'node_reference/nodes/ExportCloudToPly.md'
    - 'node_reference/nodes/ExportHeightmap.md'
    - 'node_reference/nodes/ExportNormalMap.md'
    - 'node_reference/nodes/ExportPath.md'
    - 'node_reference/nodes/ExportPointsToPly.md'
    - 'node_reference/nodes/ExportTexture.md'
    - 'node_reference/nodes/Falloff.md'
    - 'node_reference/nodes/FillTalus.md'
    - 'node_reference/nodes/FlatbedCarve.md'
    - 'node_reference/nodes/FloodingFromBoundaries.md'
    - 'node_reference/nodes/FloodingFromPoint.md'
    - 'node_reference/nodes/FloodingLakeSystem.md'
    - 'node_reference/nodes/FloodingUniformLevel.md'
    - 'node_reference/nodes/FlowStream.md'
    - 'node_reference/nodes/Fold.md'
    - 'node_reference/nodes/GaborWaveFbm.md'
    - 'node_reference/nodes/Gain.md'
    - 'node_reference/nodes/GammaCorrection.md'
    - 'node_reference/nodes/GammaCorrectionLocal.md'
    - 'node_reference/nodes/GaussianDecay.md'
    - 'node_reference/nodes/GaussianPulse.md'
    - 'node_reference/nodes/Gavoronoise.md'
    - 'node_reference/nodes/Gradient.md'
    - 'node_reference/nodes/GradientAngle.md'
    - 'node_reference/nodes/GradientNorm.md'
    - 'node_reference/nodes/GradientTalus.md'
    - 'node_reference/nodes/HeightmapToKernel.md'
    - 'node_reference/nodes/HeightmapToMask.md'
    - 'node_reference/nodes/HeightmapToNormalMap.md'
    - 'node_reference/nodes/HeightmapToRGBA.md'
    - 'node_reference/nodes/HemisphereFieldFbm.md'
    - 'node_reference/nodes/HydraulicBlur.md'
    - 'node_reference/nodes/HydraulicMusgrave.md'
    - 'node_reference/nodes/HydraulicParticle.md'
    - 'node_reference/nodes/HydraulicProcedural.md'
    - 'node_reference/nodes/HydraulicSchott.md'
    - 'node_reference/nodes/HydraulicStream.md'
    - 'node_reference/nodes/HydraulicStreamLog.md'
    - 'node_reference/nodes/HydraulicStreamUpscaleAmplification.md'
    - 'node_reference/nodes/HydraulicVpipes.md'
    - 'node_reference/nodes/ImportHeightmap.md'
    - 'node_reference/nodes/ImportTexture.md'
    - 'node_reference/nodes/Inverse.md'
    - 'node_reference/nodes/Island.md'
    - 'node_reference/nodes/IslandLandMask.md'
    - 'node_reference/nodes/KernelCupola.md'
    - 'node_reference/nodes/KernelDiskSmooth.md'
    - 'node_reference/nodes/KernelGabor.md'
    - 'node_reference/nodes/KernelPrim.md'
    - 'node_reference/nodes/KmeansClustering2.md'
    - 'node_reference/nodes/KmeansClustering3.md'
    - 'node_reference/nodes/Kuwahara.md'
    - 'node_reference/nodes/Laplace.md'
    - 'node_reference/nodes/Lerp.md'
    - 'node_reference/nodes/MakeBinary.md'
    - 'node_reference/nodes/MakePeriodic.md'
    - 'node_reference/nodes/MakePeriodicStitching.md'
    - 'node_reference/nodes/MeanShift.md'
    - 'node_reference/nodes/Median3x3.md'
    - 'node_reference/nodes/MedianPseudo.md'
    - 'node_reference/nodes/MergeWaterDepths.md'
    - 'node_reference/nodes/MixNormalMap.md'
    - 'node_reference/nodes/MixTexture.md'
    - 'node_reference/nodes/Mixer.md'
    - 'node_reference/nodes/MorphologicalGradient.md'
    - 'node_reference/nodes/MorphologicalTopHat.md'
    - 'node_reference/nodes/MountainCone.md'
    - 'node_reference/nodes/MountainInselberg.md'
    - 'node_reference/nodes/MountainRangeRadial.md'
    - 'node_reference/nodes/MountainStump.md'
    - 'node_reference/nodes/MountainTibesti.md'
    - 'node_reference/nodes/Multisteps.md'
    - 'node_reference/nodes/Noise.md'
    - 'node_reference/nodes/NoiseFbm.md'
    - 'node_reference/nodes/NoiseIq.md'
    - 'node_reference/nodes/NoiseJordan.md'
    - 'node_reference/nodes/NoiseParberry.md'
    - 'node_reference/nodes/NoisePingpong.md'
    - 'node_reference/nodes/NoiseRidged.md'
    - 'node_reference/nodes/NoiseSwiss.md'
    - 'node_reference/nodes/NormalDisplacement.md'
    - 'node_reference/nodes/NormalMapToHeightmap.md'
    - 'node_reference/nodes/Opening.md'
    - 'node_reference/nodes/Paraboloid.md'
    - 'node_reference/nodes/Path.md'
    - 'node_reference/nodes/PathBezier.md'
    - 'node_reference/nodes/PathBezierRound.md'
    - 'node_reference/nodes/PathBspline.md'
    - 'node_reference/nodes/PathDecasteljau.md'
    - 'node_reference/nodes/PathDecimate.md'
    - 'node_reference/nodes/PathDig.md'
    - 'node_reference/nodes/PathFind.md'
    - 'node_reference/nodes/PathFractalize.md'
    - 'node_reference/nodes/PathFromCsv.md'
    - 'node_reference/nodes/PathMeanderize.md'
    - 'node_reference/nodes/PathResample.md'
    - 'node_reference/nodes/PathSDF.md'
    - 'node_reference/nodes/PathShuffle.md'
    - 'node_reference/nodes/PathSmooth.md'
    - 'node_reference/nodes/PathToCloud.md'
    - 'node_reference/nodes/PathToHeightmap.md'
    - 'node_reference/nodes/Plateau.md'
    - 'node_reference/nodes/PolygonField.md'
    - 'node_reference/nodes/PolygonFieldFbm.md'
    - 'node_reference/nodes/PostProcess.md'
    - 'node_reference/nodes/Preview.md'
    - 'node_reference/nodes/ProjectTalus.md'
    - 'node_reference/nodes/QuiltingBlend.md'
    - 'node_reference/nodes/QuiltingExpand.md'
    - 'node_reference/nodes/QuiltingShuffle.md'
    - 'node_reference/nodes/RadialDisplacementToXy.md'
    - 'node_reference/nodes/RecastCanyon.md'
    - 'node_reference/nodes/RecastCliff.md'
    - 'node_reference/nodes/RecastCliffDirectional.md'
    - 'node_reference/nodes/RecastCracks.md'
    - 'node_reference/nodes/RecastSag.md'
    - 'node_reference/nodes/Receive.md'
    - 'node_reference/nodes/Recurve.md'
    - 'node_reference/nodes/RecurveKura.md'
    - 'node_reference/nodes/RecurveS.md'
    - 'node_reference/nodes/RelativeDistanceFromSkeleton.md'
    - 'node_reference/nodes/RelativeElevation.md'
    - 'node_reference/nodes/Remap.md'
    - 'node_reference/nodes/Rescale.md'
    - 'node_reference/nodes/Reverse.md'
    - 'node_reference/nodes/ReverseAboveThreshold.md'
    - 'node_reference/nodes/ReverseMidpoint.md'
    - 'node_reference/nodes/Ridgelines.md'
    - 'node_reference/nodes/Rift.md'
    - 'node_reference/nodes/Rifts.md'
    - 'node_reference/nodes/Rotate.md'
    - 'node_reference/nodes/RotateDisplacement.md'
    - 'node_reference/nodes/Ruggedness.md'
    - 'node_reference/nodes/Rugosity.md'
    - 'node_reference/nodes/Saturate.md'
    - 'node_reference/nodes/ScanMask.md'
    - 'node_reference/nodes/SedimentDeposition.md'
    - 'node_reference/nodes/SelectAngle.md'
    - 'node_reference/nodes/SelectBlobLog.md'
    - 'node_reference/nodes/SelectCavities.md'
    - 'node_reference/nodes/SelectGt.md'
    - 'node_reference/nodes/SelectInterval.md'
    - 'node_reference/nodes/SelectInwardOutward.md'
    - 'node_reference/nodes/SelectMidrange.md'
    - 'node_reference/nodes/SelectMultiband3.md'
    - 'node_reference/nodes/SelectPulse.md'
    - 'node_reference/nodes/SelectRivers.md'
    - 'node_reference/nodes/SelectSlope.md'
    - 'node_reference/nodes/SelectSoilFlow.md'
    - 'node_reference/nodes/SelectSoilRocks.md'
    - 'node_reference/nodes/SelectSoilWeathered.md'
    - 'node_reference/nodes/SelectTransitions.md'
    - 'node_reference/nodes/SelectValley.md'
    - 'node_reference/nodes/SetAlpha.md'
    - 'node_reference/nodes/SetBorders.md'
    - 'node_reference/nodes/ShapeIndex.md'
    - 'node_reference/nodes/SharpenCone.md'
    - 'node_reference/nodes/ShatteredPeak.md'
    - 'node_reference/nodes/ShiftElevation.md'
    - 'node_reference/nodes/Skeleton.md'
    - 'node_reference/nodes/Slope.md'
    - 'node_reference/nodes/SmoothCpulse.md'
    - 'node_reference/nodes/SmoothFill.md'
    - 'node_reference/nodes/SmoothFillHoles.md'
    - 'node_reference/nodes/SmoothFillSmearPeaks.md'
    - 'node_reference/nodes/Smoothstep.md'
    - 'node_reference/nodes/Stamping.md'
    - 'node_reference/nodes/StdLocal.md'
    - 'node_reference/nodes/SteepenConvective.md'
    - 'node_reference/nodes/Step.md'
    - 'node_reference/nodes/Strata.md'
    - 'node_reference/nodes/Stratify.md'
    - 'node_reference/nodes/StratifyMultiscale.md'
    - 'node_reference/nodes/StratifyOblique.md'
    - 'node_reference/nodes/Terrace.md'
    - 'node_reference/nodes/TextureAdvectionParticle.md'
    - 'node_reference/nodes/TextureAdvectionWarp.md'
    - 'node_reference/nodes/TextureQuiltingExpand.md'
    - 'node_reference/nodes/TextureQuiltingShuffle.md'
    - 'node_reference/nodes/TextureSplitChannels.md'
    - 'node_reference/nodes/TextureToHeightmap.md'
    - 'node_reference/nodes/TextureUvChecker.md'
    - 'node_reference/nodes/Thermal.md'
    - 'node_reference/nodes/ThermalFlatten.md'
    - 'node_reference/nodes/ThermalScree.md'
    - 'node_reference/nodes/Thru.md'
    - 'node_reference/nodes/Toggle.md'
    - 'node_reference/nodes/Transfer.md'
    - 'node_reference/nodes/Translate.md'
    - 'node_reference/nodes/Unsphericity.md'
    - 'node_reference/nodes/ValleyFill.md'
    - 'node_reference/nodes/ValleyWidth.md'
    - 'node_reference/nodes/Vorolines.md'
    - 'node_reference/nodes/VorolinesFbm.md'
    - 'node_reference/nodes/Voronoi.md'
    - 'node_reference/nodes/VoronoiFbm.md'
    - 'node_reference/nodes/Voronoise.md'
    - 'node_reference/nodes/Vororand.md'
    - 'node_reference/nodes/Warp.md'
    - 'node_reference/nodes/WarpDownslope.md'
    - 'node_reference/nodes/WaterDepthDryOut.md'
    - 'node_reference/nodes/WaterDepthFromMask.md'
    - 'node_reference/nodes/WaterMask.md'
    - 'node_reference/nodes/WaveDune.md'
    - 'node_reference/nodes/WaveSine.md'
    - 'node_reference/nodes/WaveSquare.md'
    - 'node_reference/nodes/WaveTriangular.md'
    - 'node_reference/nodes/WaveletNoise.md'
    - 'node_reference/nodes/White.md'
    - 'node_reference/nodes/WhiteDensityMap.md'
    - 'node_reference/nodes/WhiteSparse.md'
    - 'node_reference/nodes/Wrinkle.md'
    - 'node_reference/nodes/ZScore.md'
    - 'node_reference/nodes/ZeroedEdges.md'
    - 'node_reference/nodes/Zoom.md'

